### ISSUE TITLE
Support windows server nodes

### ISSUE THREAD

**Issue by rhockenbury** [kubernetes/cloud-provider-vsphere#291]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

Add support for running the CPI on windows server nodes.   This would require publishing a windows image for the CPI, and modifying the Helm chart to add a daemonset to run the windows CPI on windows node.

This would bring the CPI inline with the in-tree VCP, which supported windows.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dvonthenen** [comment]
This issue captures the current status: https://github.com/kubernetes/cloud-provider-vsphere/issues/201

There shouldn't be any reason why the current v1.1 release of the CPI wouldn't work with Windows-based Kubernetes cluster. We should just need someone to validate if it works (or not - and if not, logs would be helpful). Windows images should not be required for the CPI. Is there a particular reason why Windows images are specifically being called out for the CPI?

The CSI side might be a different story because of the Windows volume mounts, but that issue would need to be filed in the CSI repo (https://github.com/kubernetes-sigs/vsphere-csi-driver/) to get the correct visibility. A different team works on the storage/CSI side of things.

**Comment by rhockenbury** [comment]
Thanks.  Misunderstanding on my part 😊- I had quickly looked at the helm chart and saw a daemonset (assuming it needs to run on all nodes), but yes, now I see that it has a nodeselector for the masters.  Windows images are not required then.

I plan to test this out on a cluster with windows nodes. 

For the CSI, I had created an issue over there already - https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/123.

**Comment by dvonthenen** [comment]
Thanks @rhockenbury! The validation would be invaluable since I don't have access to a Windows k8s cluster and don't current have resource to check it.
