### ISSUE TITLE
Version compatibility for NSX-T LoadBalancer

### ISSUE THREAD

**Issue by onesolpark** [kubernetes/cloud-provider-vsphere#306]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
#292
I saw that the nsx-t implementation for Service type:LoadBalancer was merged a couple of weeks ago.
 

I want to test the implementation on our environment.
I was just wondering if there is there a minimum version requirement for NSX-T 
and which NSX-T versions are compatible with the current feature.

**What you expected to happen**:
Documentation on minimum version and version compatibility for NSX-T

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Comment by dvonthenen** [comment]
The current compatibility is with NSX-T 2.5 only. The feature is only listed as alpha just to set expectations on how it's going to work. Since the feature is new, expect an evolving set of changes with the implementation. Will list the compatibility with the feature in the release notes when the next version of the CPI is cut.

If you have any other questions, you can find me in k8s slack!

**Comment by dvonthenen** [comment]
Will check the docs and update if this isn't clear
