### ISSUE TITLE
Port Zones support to out-of-tree CCM

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#36]
Zones support is currently under review in the in-tree provider and will most likely be included in the 1.12 release (ref. kubernetes/kubernetes#66795).

This issue tracks the porting of the feature over to the out-of-tree CCM hosted in this repo.

/kind feature

**Comment by embano1** [comment]
// For the case of external cloud providers, use GetZoneByProviderID or GetZoneByNodeName since GetZone
	// can no longer be called from the kubelets.
https://github.com/kubernetes/kubernetes/blob/de1656abbb5ce07bbc5dc38332ad3602c0d95396/pkg/cloudprovider/cloud.go#L205

This is not implemented via the new in-tree zones support and thus has to be added when porting VCP Zones. 
https://github.com/kubernetes/kubernetes/blob/008165027b32db28d447eeaa0995fb686c6a18c1/pkg/cloudprovider/providers/vsphere/vsphere.go#L1409

**Comment by embano1** [comment]
A new issue we're working on in the in-tree cloud provider for tracking purposes here: https://github.com/kubernetes/kubernetes/issues/67703

**Comment by dougm** [comment]
Updates from in-tree that will apply here:

- Finalized the govmomi tags API: https://github.com/kubernetes/kubernetes/pull/67722

- Added tags API support to vcsim and VCP Zones tests against it: https://github.com/kubernetes/kubernetes/pull/67741

- Added support for tagging any level in the hierarchy:  https://github.com/kubernetes/kubernetes/pull/67787

Currently in progress, SSO support for vAPI: https://github.com/vmware/govmomi/issues/1179

The in-tree implementation currently requires credentials in the kubelet node configuration.
When we port Zones support to the external provider, this issue goes away thanks to `GetZoneByProviderID` and `GetZoneByNodeName` being called from CCM - no kubelet config required.

Once SSO support is completed, I expect porting Zones support to be straight forward.

**Comment by dvonthenen** [comment]
Will be working on this because I am looking at multi-VC/DC support in the CSI implementation.

**Comment by dvonthenen** [comment]
Finished implementation... Currently testing.

**Comment by dvonthenen** [comment]
PR https://github.com/kubernetes/cloud-provider-vsphere/pull/130
