### ISSUE TITLE
Implement E2E tests using vcsim

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#37]
We need end-to-end tests for the cloud provider code to provide functional testing against a real vSphere API endpoint.

Currently the CCM has no E2E tests, we should implement an initial set of E2E tests for it, these tests should be part of a new Makefile target that will automatically run as part of a new CI job.

- [ ] Implement E2E tests using vcsim
- [ ] Create `Makefile` target for E2E tests
- [ ] Create a new job in `kubernetes/test-infra` for E2E tests and make it run at every PR

/kind feature

**Comment by frapposelli** [comment]
FYI @akutz

**Comment by dvonthenen** [comment]
Just leaving a comment based on the discussion in the monthly cloud-provider-vsphere meeting. With the recent merge of the following PRs (https://github.com/kubernetes/cloud-provider-vsphere/pull/147 and https://github.com/kubernetes/cloud-provider-vsphere/pull/149) combined with the existing go tests in place, the vcsim e2e tests are looking pretty good at this point. If there are additional specific tests that we need, please comment here and we can look at implementing them. Otherwise, the action based on the discussion in the meeting will be to close this out as completed.

NOTE: There is another issue, https://github.com/kubernetes/cloud-provider-vsphere/issues/75, which captures e2e tests on real physical infrastructure and is orthogonal to this vcsim e2e tests issue.

**Comment by frapposelli** [comment]
based on @dvonthenen last comment and PR #155 being merged, we can

/close

this one.
