### ISSUE TITLE
Tool for converting INI cloud config to YAML

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/cloud-provider-vsphere#371]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

We recently added support to use YAML for the cloud configuration file. We now support both INI and YAML but YAML is preferred. It would be useful to users to have a tool to convert an existing INI file to YAML.

**Comment by dvonthenen** [comment]
Instead of writing go code that we would need to maintain... I would be in favor of having an online tool in the Docs where we convert INI to YAML. Placing this tool just after the YAML configuration would be a great place for it. Doing this would potentially allow someone to work on this as a good first issue to tackle.
