### ISSUE TITLE
Config viperization/consolidation: needs to be abstracted away from env vars (or at least LookupEnv should happen in one place)

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/cloud-provider-vsphere#393]
**What happened**:
Were about to add dual stack to this cloud provider, but as of now weve got some drift around where the configs coming from external are stored: 
```
pkg/cloudprovider/vsphere/cloud.go:     if _, ok := os.LookupEnv("ENABLE_ALPHA_NSXT_LB"); ok {
pkg/cloudprovider/vsphere/instances.go: if _, ok := os.LookupEnv("SKIP_NODE_DELETION"); ok {
```

**What you expected to happen**:

env vars should probably be parsed into a global config object w a validateconfig func 

**How to reproduce it (as minimally and precisely as possible)**:

grep :) 

**Anything else we need to know?**:

**Environment**:
- vsphere-cloud-controller-manager version: master

**Comment by jayunit100** [comment]
i guess if we want lightweight something as simple as 

```
VSphereConfig struct {
EnableAlpha string
SkipNodeDel string
EnableDualStack string
}
```

followed by

```
func init() {
   v := ..
   v.SkipNodeDel = os.LookupEnv("SKIP_NODE_DELETION")
   v.EnableDualStack = os.LookupEnv("...")
}
```

but if we suspect more sophisticated config in the future something like viper (https://github.com/spf13/viper) could be used to do this automagically.

**Comment by dvonthenen** [comment]
We do have the ENVVARs in 2 main locations depending on if the setting is common or not... we just got a little lazy with the `SKIP_NODE_DELETION` flag because we through it was going to be just a temporary one-off flag for a single release.

You can find the CPI and common vars:
CPI specific envvars - https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/cloudprovider/vsphere/config/config.go
Common envvars - https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/common/config/config.go

If we do have a permanent flag, we should move them into those files.
