### ISSUE TITLE
gcr.io/cloud-provider-vsphere/cpi/release/manager:latest is tagged to very old image v1.2.1

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/cloud-provider-vsphere#483]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
`gcr.io/cloud-provider-vsphere/cpi/release/manager:latest` is tagged to very old image `gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.2.1`

**What you expected to happen**:
Can we correct the latest tag to point to `gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.21.0`

cc: @andrewsykim

**Comment by andrewsykim** [comment]
Hi @divyenpatel we intentionally stopped pushing to latest because folks were pulling the latest image _without_ updating their manifests accordingly which lead to breaking changes. The recommendation going forward is to use a tagged version based on the kubernetes version of the cluster (major and minors should match)
