### ISSUE TITLE
Return descriptive vm size when calling InstanceType()

### ISSUE THREAD

**Issue by frapposelli** [kubernetes/cloud-provider-vsphere#55]
Currently when calling `InstanceType()` we simply return `vsphere-vm`, this does not help the user in identifying the type of VM that the k8s node is running on.

As vSphere doesn't have t-shirt size instances, we should come up with a meaningful expression of the vm size to be reported as string.

Some ideas (assuming a VM with 4 vCPU and 8GB of RAM):

- `vsphere.4c8192m` 
- `vm-4cpu8192mem`
- `vm.4c8m`
- `vm.4c8gb`
- `vm.4cpu-8gb`
- `vsphere-vm.4cpu-8gb`

/kind feature
/cc @dvonthenen @dougm @akutz

**Comment by dvonthenen** [comment]
This should be fairly easy to do since we are already pulling the guest info for NodeManager.

I think the following string should be very easy to parse:
vsphere-vm.cpu-4.mem-8gb.os-rhel

Making the format: key-value.key-value.key-value (etc, etc) allows for a generic key/value format in which order doesn't matter.
