### ISSUE TITLE
restrict to deploy daemonset vsphere-csi-node on baremetal nodes

### ISSUE THREAD

**Issue by allanian** [kubernetes/cloud-provider-vsphere#684]
### What would you like to be added?

Hello, i was create a k8s cluster with 8 vsphere nodes and 3 baremetal, now i getting issue, vpshere daemonset will try to deploy on baremetal and getting error.
How i can restrict daemonset vsphere-csi-node to dont deploy on baremetal nodes?

### Why is this needed?

Now its failing and restarting.

**Comment by lubronzhan** [comment]
You mean vsphere-csi-node?
You could try 
1. Add label to your baremetal node, and add selector to the csi manifest to only deploy on the node with specific label
2. add tains to the baremetal node, but this would be little more tricky since for pod that you want to deploy on the baremetal node, you have to add tolerations
